/**
 * @author Tobias
 */
package mainPackage;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;

public class Jframe_Main extends javax.swing.JFrame {
    
    //String projectName;
    ControlEngine engine;
    DefaultListModel listModel;
    
    public Jframe_Main() {
        initComponents();
        listModel = new DefaultListModel();
        jList_projectList.setModel(listModel);
        
        hideEditDelete();
        hideCreate();
        engine = new ControlEngine();
        
        
        addMouseListener();
        
        if (jList_projectList.isSelectionEmpty() == false) {
            System.out.println("Something is selected");
                    
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_create = new javax.swing.JButton();
        jButton_start = new javax.swing.JButton();
        jLabel_timer = new javax.swing.JLabel();
        jTextField_projectName = new javax.swing.JTextField();
        jButton_cancel = new javax.swing.JButton();
        jButton_confirm = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_projectList = new javax.swing.JList();
        jButton_edit = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_create.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_create.setText("Create project");
        jButton_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jButton_start.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_start.setText("START");
        getContentPane().add(jButton_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jLabel_timer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_timer.setText("Timer");
        jLabel_timer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel_timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 90, 40));

        jTextField_projectName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_projectName.setText("enter project name");
        jTextField_projectName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_projectNameMousePressed(evt);
            }
        });
        jTextField_projectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_projectNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_projectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 168, -1));

        jButton_cancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_cancel.setText("cancel");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jButton_confirm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_confirm.setText("confirm");
        jButton_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_confirmActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jScrollPane2.setViewportView(jList_projectList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 460, -1));

        jButton_edit.setText("Edit");
        getContentPane().add(jButton_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jButton_delete.setText("Delete");
        getContentPane().add(jButton_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createActionPerformed
        jTextField_projectName.setText("enter project name");
        showCreate();
    }//GEN-LAST:event_jButton_createActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        hideCreate();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jButton_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_confirmActionPerformed
        String projectName = jTextField_projectName.getText();
        engine.createProject("Project: " + projectName, "Session: " + "00:00:00", "Total: " + "00:00:00");
        jTextField_projectName.setText("");
        listModel.clear();
        
        for (int i = 0; i < engine.getProject().size(); i++) {
            listModel.addElement(engine.getProject().get(i));
        }
        hideCreate();
        
    }//GEN-LAST:event_jButton_confirmActionPerformed

    private void jTextField_projectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_projectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_projectNameActionPerformed

    private void jTextField_projectNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_projectNameMousePressed
        jTextField_projectName.setText("");
    }//GEN-LAST:event_jTextField_projectNameMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe_Main().setVisible(true);
            }
        });
    }
    
    private void hideCreate() {
        jTextField_projectName.setVisible(false);
        jButton_confirm.setVisible(false);
        jButton_cancel.setVisible(false);
    }
    
    private void showCreate() {
        jTextField_projectName.setVisible(true);
        jButton_confirm.setVisible(true);
        jButton_cancel.setVisible(true);
    }
    
    private void deleteProject() {
        int index = jList_projectList.getSelectedIndex();
        listModel.remove(index);
        engine.getProject().remove(index);
    }
    
    private void hideEditDelete() {
        jButton_edit.setVisible(false);
        jButton_delete.setVisible(false);
    }
    
    private void addMouseListener() {
    this.addMouseListener(new MouseAdapter() {
    public void mouseClicked(MouseEvent e){
        System.out.println("Mouse was clicked on my frame!");
        if (jList_projectList.isSelectionEmpty() == false) {
            System.out.println("Something is selected");
                    
        }
    }
});
    }
    
    private void checkListSelected() {
        
    }
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_confirm;
    private javax.swing.JButton jButton_create;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_start;
    private javax.swing.JLabel jLabel_timer;
    private javax.swing.JList jList_projectList;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_projectName;
    // End of variables declaration//GEN-END:variables
}
